// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Camera_46cd690149dfe934ebe8093c607e8d63Index = 0;
		public const int ClientConnection_99b82a7eed3651b419f5350c1e133f4eIndex = 1;
		public const int Player_a26d02a2f63fd174f8b2dce76dc412a9Index = 2;
		public const int ScoreBoard_1155d03ea10e86c4b8d8196ccbc3f483Index = 3;
		public const int SkeleSpawner_381a2c25330358c48abb7579981b3e77Index = 4;
		public const int Skeleton_1a31f1e946b732a47aba5db2fad6053dIndex = 5;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Camera_46cd690149dfe934ebe8093c607e8d63", 0 },

			{ "ClientConnection_99b82a7eed3651b419f5350c1e133f4e", 1 },

			{ "Player_a26d02a2f63fd174f8b2dce76dc412a9", 2 },

			{ "ScoreBoard_1155d03ea10e86c4b8d8196ccbc3f483", 3 },

			{ "SkeleSpawner_381a2c25330358c48abb7579981b3e77", 4 },

			{ "Skeleton_1a31f1e946b732a47aba5db2fad6053d", 5 },

		};
	}
}
