// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Canvas_f09cd457a34a6d74f80cf453e6b14dedIndex = 0;
		public const int Player_a26d02a2f63fd174f8b2dce76dc412a9Index = 1;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Canvas_f09cd457a34a6d74f80cf453e6b14ded", 0 },

			{ "Player_a26d02a2f63fd174f8b2dce76dc412a9", 1 },

		};
	}
}
