// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct ClientConnection_Client_8466908635430828435 : ICoherenceComponentData
	{
		public string clientName;

		public override string ToString()
		{
			return $"ClientConnection_Client_8466908635430828435(clientName: {clientName})";
		}

		public uint GetComponentType() => Definition.InternalClientConnection_Client_8466908635430828435;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (ClientConnection_Client_8466908635430828435)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				clientName = other.clientName;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static void Serialize(ClientConnection_Client_8466908635430828435 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteShortString(data.clientName);
			}
			mask >>= 1;
		}

		public static (ClientConnection_Client_8466908635430828435, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new ClientConnection_Client_8466908635430828435();
	
			if (bitStream.ReadMask())
			{
				val.clientName = bitStream.ReadShortString();
				mask |= 0b00000000000000000000000000000001;
			}
			return (val, mask, null);
		}
		public static (ClientConnection_Client_8466908635430828435, uint, uint?) DeserializeArchetypeClientConnection_99b82a7eed3651b419f5350c1e133f4e_ClientConnection_Client_8466908635430828435_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new ClientConnection_Client_8466908635430828435();
			if (bitStream.ReadMask())
			{
				val.clientName = bitStream.ReadShortString();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as ClientConnection_Client_8466908635430828435?;
	
		}
	}
}