// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_id0_PlayerScript__char_46_kill_f1269c51_4f2b_4e79_84a8_5f95b2752104 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalPlayer_id0_PlayerScript__char_46_kill_f1269c51_4f2b_4e79_84a8_5f95b2752104;

		public static void Serialize(Player_id0_PlayerScript__char_46_kill_f1269c51_4f2b_4e79_84a8_5f95b2752104 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Player_id0_PlayerScript__char_46_kill_f1269c51_4f2b_4e79_84a8_5f95b2752104 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Player_id0_PlayerScript__char_46_kill_f1269c51_4f2b_4e79_84a8_5f95b2752104
			(
			){};
		}
	}
}
