// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct ScoreBoard_ScoreBoardScript__char_46_reBuildList_bd5d9a95_c3e9_4c8d_9736_02bde17cffd0 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalScoreBoard_ScoreBoardScript__char_46_reBuildList_bd5d9a95_c3e9_4c8d_9736_02bde17cffd0;

		public static void Serialize(ScoreBoard_ScoreBoardScript__char_46_reBuildList_bd5d9a95_c3e9_4c8d_9736_02bde17cffd0 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static ScoreBoard_ScoreBoardScript__char_46_reBuildList_bd5d9a95_c3e9_4c8d_9736_02bde17cffd0 Deserialize(IInProtocolBitStream bitStream)
		{

			return new ScoreBoard_ScoreBoardScript__char_46_reBuildList_bd5d9a95_c3e9_4c8d_9736_02bde17cffd0
			(
			){};
		}
	}
}
